/*
 * Stoatworks Labs - About window data for nib.
 *
 * Normally GENERATED by stoatworks-backend/scripts/sync-about.py from the
 * website's projects.json, which is the one place these facts are written
 * down. This copy is HAND-WRITTEN, in the generated file's exact shape,
 * because nib has no projects.json entry yet. It is deliberately absent from
 * the sync's TARGETS table for the same reason -- a row there could only ever
 * print a skip, and a table that always warns stops being read. Add the row,
 * and delete this paragraph, once the website page exists.
 *
 * `guide` and `page` are empty rather than the URLs those pages will
 * eventually have: StoatworksAboutParams.h leaves a missing link out of the
 * button list entirely, which is right, because a button that opens a 404 is
 * worse than no button.
 *
 * `version` here is a fallback. Anything with a build step injects the real
 * one at build time and overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "nib";
    inline constexpr auto slug = "nib";
    inline constexpr auto hook = "Line drawing for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/nib";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
